name: Draft tags/release versions
run-name: ${{ github.actor }} ${{ github.base_ref }} ${{ github.head_ref }} ${{ github.ref }}is testing release drafter on the develop branch
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
permissions:
  contents: read
jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: draft for develop
        if: startsWith(github.base_ref, 'develop')
        uses: release-drafter/release-drafter@v5
        with:
          tag: 'alpha ${{ env.RELEASE_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Gets latest created release info
        id: latest_release_info
        uses: ctrlaltdev/latest-release-json-action@v1.0.1
        with:
          releases: '[...]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something with your bumped release version
        run: echo ${{ steps.latest_release_info.outputs.tag }}
      # - name: Gets latest created release info
      #   id: latest_release_info
      #   uses: dave-ohouse/action-latest-release-info@v0.0.3
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      - name: Bump release version
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ steps.latest_release_info.outputs.tag }}
          increment-version-fragment: 'MINOR'
          prerelease-fragment: 'ALPHA'

      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.updated-version }}

      - name: draft for qa
        if: startsWith(github.base_ref, 'qa')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version.outputs.updated-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 