name: Draft tags/release versions
run-name: ${{ github.actor }} ${{ github.repository }} is testing release drafter on the develop branch
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
permissions:
  contents: read
jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get latest release
        id: latest_release
        uses: rez0n/actions-github-release@v1.8
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "github0389/terraform-exercise"
          type: "latest"

      - name: stripp "v" in the version release
        env:
          TAG: ${{ steps.latest_release.outputs.release }} 
        run: echo "TAG=${TAG#v.}" >> $GITHUB_ENV

      - name: echo release version
        run: echo ${{ env.TAG }}

      - name: Bump release version
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ env.TAG }}
          increment-version-fragment: 'MINOR'
          prerelease-fragment: 'ALPHA'

      - name: echo bumped release version
        run: echo ${{ steps.bump_version.outputs.updated-version }}

      - name: draft release for pull request on qa
        if: startsWith(github.base_ref, 'main')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version.outputs.updated-version }}

      - name: draft for pull request on develop
        if: startsWith(github.base_ref, 'develop')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version.outputs.updated-version }}