name: Draft tags/release versions
run-name: ${{ github.actor }} ${{ github.repository }} is testing release drafter on the develop branch
on:
  # push:
  #   branches:
  #     - develop
  #     - main
  pull_request:
    branches:
      - develop
      - main
permissions:
  contents: read
jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get latest release
        id: latest_release
        uses: rez0n/actions-github-release@v1.8
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "github0389/terraform-exercise"
          type: "latest"

      - name: stripp "v" in the version release
        env:
          TAG: ${{ steps.latest_release.outputs.release }} 
        run: echo "TAG=${TAG#v.}" >> $GITHUB_ENV

      - name: echo release version
        run: echo ${{ env.TAG }}

      - name: generate alpha release version
        id: bump_version_alpha
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ env.TAG }}
          increment-version-fragment: 'MAJOR'
          prerelease-fragment: 'ALPHA'

      - name: generate beta release version
        id: bump_version_beta
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ env.TAG }}
          increment-version-fragment: 'MAJOR'
          prerelease-fragment: 'BETA'
      
      - name: generate rc release version
        id: bump_version_rc
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ env.TAG }}
          increment-version-fragment: 'MAJOR'
          prerelease-fragment: 'RC'

      - name: draft for pull request on develop
        if: startsWith(github.base_ref, 'develop')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version_alpha.outputs.updated-version }}

      - name: draft release for pull request on Test
        if: startsWith(github.base_ref, 'test')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version_beta.outputs.updated-version }}

      - name: draft release for pull request on QA
        if: startsWith(github.base_ref, 'qa')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version_rc.outputs.updated-version }}

      - name: draft release for pull request on PROD
        if: startsWith(github.base_ref, 'prod')
        uses: release-drafter/release-drafter@v5