name: Draft tags/release versions
run-name: ${{ github.actor }} ${{ github.repository }} is testing release drafter on the develop branch
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
permissions:
  contents: read
jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: rez0n/actions-github-release@v1.8
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "github0389/terraform-exercise"
          type: "latest"
      
      # - name: set latest release/TAG
      #   id: latest_release
      #   run: echo '::set-output name=tag::${{ steps.latest_release_info.outputs.release }}'

      - name: remove v
        id: latest_release
        env:
          TAG: ${{ steps.latest_release_info.outputs.release }} 
        run: echo "TAG=${TAG#v.}" >> $GITHUB_ENV

      - name: echo release version
        run: echo ${{ TAG }}

      - name: Bump release version
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ TAG }}
          increment-version-fragment: 'MINOR'
          prerelease-fragment: 'ALPHA'

      - name: echo bumped release version
        run: echo ${{ steps.bump_version.outputs.updated-version }}

      - name: draft for qa
        if: startsWith(github.base_ref, 'qa')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version.outputs.updated-version }}

      - name: draft for develop
        if: startsWith(github.base_ref, 'develop')
        uses: release-drafter/release-drafter@v5
        with:
          tag: 'alpha ${{ env.RELEASE_VERSION }}'