name: Draft tags/release versions
run-name: ${{ github.actor }} ${{ github.repository }} is testing release drafter on the develop branch
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
permissions:
  contents: read
jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: latest_release_info
        uses: rez0n/actions-github-release@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "github0389/terraform-exercise"
          type: "latest"
      
      - name: remove v
        id: latest_release
        uses: ctrlaltdev/latest-release-json-action@v1.0.1
        with:
          releases: '[ ${{ steps.latest_release_info.outputs.release }} ]'

      - name: echo release version
        run: echo ${{ steps.latest_release.outputs.tag}}
        #run: echo ${{ github.repository }}

      # - name: Gets latest created release info
      #   id: latest_release_info
      #   uses: dave-ohouse/action-latest-release-info@v0.0.3
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      - name: Bump release version
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ steps.latest_release.outputs.tag }}
          increment-version-fragment: 'MINOR'
          prerelease-fragment: 'ALPHA'

      - name: echo bumped release version
        run: echo ${{ steps.bump_version.outputs.updated-version }}

      - name: draft for qa
        if: startsWith(github.base_ref, 'qa')
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.bump_version.outputs.updated-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: draft for develop
        if: startsWith(github.base_ref, 'develop')
        uses: release-drafter/release-drafter@v5
        with:
          tag: 'alpha ${{ env.RELEASE_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}