name: Draft tags/release versions
run-name: ${{ github.actor }} ${{ github.base_ref }} ${{ github.head_ref }} ${{ github.ref }}is testing release drafter on the develop branch
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
permissions:
  contents: read
jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: draft for develop
        if: startsWith(github.base_ref, 'develop')
        uses: release-drafter/release-drafter@v5
        with:
          tag: 'alpha ${{ env.RELEASE_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: draft for qa
        if: startsWith(github.base_ref, 'main')
        uses: release-drafter/release-drafter@v5
        with:
          tag: format('beta{0}',{{ env.RELEASE_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 